development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url:  redis://redistogo:9ce5489d8bb3dd89dd6e90a767b657ff@angelfish.redistogo.com:11904/
  channel_prefix: play_ball_production
